name: SafeHaven
version: '0.02-ALPHA'
main: oi.yeetaaron1.org.SafeHaven
api-version: '1.21'
authors: [ yeetaaron1 ]
description: Safe haven for your friends :)
website: https://github.com/yeetaaron1/SafeHaven



commands:
  safehaven:
    description: Reloads the plugin configuration
    usage: /safehaven <admin_command>
    permission: safehaven.admin




permissions:
  safehaven.sethome:
    description: Allows the player to set homes.
    default: true

  safehaven.home:
    description: Allows the player to teleport to homes.
    default: true

  safehaven.delhome:
    description: Allows the player to delete homes.
    default: true

  safehaven.homes:
    description: Allows the player to list their homes.
    default: true
