home-system:
  max-homes: 10
  storage-method: YAML # Options: YAML, MySQL, SQLite

database:
  mysql:
    url: jdbc:mysql://localhost:3306/your_database
    user: your_username
    password: your_password
  sqlite:
    file: database.db