name: SafeHaven
version: '0.02-ALPHA'
main: oi.yeetaaron1.org.SafeHaven
api-version: '1.21'
authors: [ yeetaaron1 ]
description: Safe haven for your friends :)
website: https://github.com/yeetaaron1/SafeHaven



commands:
  safehaven:
    description: Reloads the plugin configuration
    usage: /safehaven <admin_command>
    permission: safehaven.admin
